use osgi version 5.0.0 due to compatibility issues with pax
In case of downgrade for the version 4.3.1 (the same used by ipojo) a not method found is raised by pax:

ERROR: Bundle org.ops4j.pax.exam [1] Error starting link:classpath:META-INF/links/org.ops4j.pax.exam.link (java.lang.NoSuchMethodError: org.osgi.framework.wiring.BundleWire.getProvider()Lorg/osgi/framework/wiring/BundleRevision;)
java.lang.NoSuchMethodError: org.osgi.framework.wiring.BundleWire.getProvider()Lorg/osgi/framework/wiring/BundleRevision;
	at org.apache.felix.framework.BundleRevisionDependencies.addDependent(BundleRevisionDependencies.java:44)
	at org.apache.felix.framework.StatefulResolver.markResolvedRevisions(StatefulResolver.java:998)
	at org.apache.felix.framework.StatefulResolver.resolve(StatefulResolver.java:427)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3967)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1291)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:722)